
import { FundingType, FundingOpportunityDb, Achievement } from './types';

export const MOCK_FUNDING: FundingOpportunityDb[] = [
  {
    opportunity_id: 'nyda_grant_001',
    programme_name: 'NYDA Micro Finance Grant',
    issuer_name: 'National Youth Development Agency (NYDA)',
    issuer_type: 'Government Agency',
    official_status: true,
    status: 'OPEN',
    funding_type: FundingType.GRANT,
    target_stage: 'Early Stage',
    legal_form_required: ['Private Company', 'Sole Proprietor', 'Cooperative'],
    sector_tags: ['Any'],
    geo_scope: 'National',
    amount_min: 1000,
    amount_max: 200000,
    non_cash_support: 'Business Management Training',
    eligibility_summary: 'Targeted at youth entrepreneurs (18-35 years) to acquire equipment, stock, or formalization. Must possess skills or experience related to the business.',
    required_documents: ['ID', 'Proof of Address', 'Business Plan', 'Quotations', 'Banking Details'],
    application_url: 'https://erp.nyda.gov.za/',
    pdf_form_url: '/assets/forms/nyda-grant-application.pdf',
    logo_url: '/assets/logos/nyda-logo.png',
    source_url: 'https://www.nyda.gov.za/',
    closing_date: 'Rolling',
    frequency: 'Rolling, Batch-based',
    expected_open_month: 'January',
    typical_duration_days: 90,
    preparation_checklist: ['Complete NYDA Business Management Training Course', 'Get 3 formal quotes for equipment/stock', 'Ensure tax clearance is valid', 'Update business plan tailored to NYDA template'],
    common_rejection_reasons: ['Quotes not from official registered suppliers', 'Applicant over 35 years old', 'Missing NYDA training certificate'],
    contact_email: 'info@nyda.gov.za',
    contact_phone: '0800 52 52 52',
    last_verified_at: '2026-05-26T00:00:00Z',
    verification_notes: 'Verified via ERP portal. Currently open for batch processing.',
    confidence_score: 98
  },
  {
    opportunity_id: 'tia_seed_002',
    programme_name: 'TIA Seed Fund',
    issuer_name: 'Technology Innovation Agency',
    issuer_type: 'Government Agency',
    official_status: true,
    status: 'UPCOMING',
    funding_type: FundingType.GRANT,
    target_stage: 'Concept/Prototype',
    legal_form_required: ['Private Company'],
    sector_tags: ['Technology', 'Innovation', 'BioTech', 'ICT'],
    geo_scope: 'National',
    amount_min: 50000,
    amount_max: 500000,
    non_cash_support: 'Incubation Support',
    eligibility_summary: 'Designed to assist technology innovators and SMMEs to advance their R&D, and validate prototypes.',
    required_documents: ['CIPC', 'Tax Clearance', 'Pitch Deck', 'IP Registration', 'Detailed Budget'],
    application_url: 'https://www.tia.org.za/seed-fund/',
    source_url: 'https://www.tia.org.za',
    closing_date: '2026-09-30',
    frequency: 'Annual',
    expected_open_month: 'September',
    typical_duration_days: 90,
    preparation_checklist: ['Draft a clear R&D milestone plan', 'Prepare technical proof of concept documentation'],
    common_rejection_reasons: ['Technology is not sufficiently innovative', 'Lack of commercialization strategy'],
    contact_email: 'customerservice@tia.org.za',
    contact_phone: '012 472 2701',
    last_verified_at: '2026-05-26T00:00:00Z',
    verification_notes: 'Opening in September. Partner directly with an implementing tech agency.',
    confidence_score: 95
  },
  {
    opportunity_id: 'sefa_direct_003',
    programme_name: 'Sefa / SEDFA Direct Lending',
    issuer_name: 'Small Enterprise Finance Agency',
    issuer_type: 'National DFI',
    official_status: true,
    status: 'OPEN',
    funding_type: FundingType.LOAN,
    target_stage: 'Growth',
    legal_form_required: ['Private Company', 'Close Corporation', 'Cooperative'],
    sector_tags: ['Manufacturing', 'Agriculture', 'Services'],
    geo_scope: 'National',
    amount_min: 50000,
    amount_max: 15000000,
    non_cash_support: 'Mentorship',
    eligibility_summary: 'Bridging loans, term loans, and revolving credit for SMMEs needing working capital or asset finance.',
    required_documents: ['CIPC', 'Tax Clearance', 'FICA', 'Management Accounts'],
    application_url: 'https://www.sefa.org.za/products/direct-lending',
    source_url: 'https://www.sefa.org.za',
    closing_date: 'Rolling',
    frequency: 'Always Open',
    expected_open_month: 'January',
    typical_duration_days: 120,
    preparation_checklist: ['Ensure management accounts are updated', 'Prepare cash flow forecast matching loan terms'],
    common_rejection_reasons: ['Poor credit record of directors', 'Unrealistic financial projections'],
    contact_email: 'helpline@sedfa.org.za',
    contact_phone: '012 748 9600',
    last_verified_at: '2026-05-26T00:00:00Z',
    verification_notes: 'Merged entity into SEDFA. Processing times can be lengthy.',
    confidence_score: 90
  },
  {
    opportunity_id: 'nef_general_004',
    programme_name: 'NEF Empowerment Funds',
    issuer_name: 'National Empowerment Fund (NEF)',
    issuer_type: 'National DFI',
    official_status: true,
    status: 'OPEN',
    funding_type: FundingType.LOAN,
    target_stage: 'Growth',
    legal_form_required: ['Private Company', 'Close Corporation'],
    sector_tags: ['Various'],
    geo_scope: 'National',
    amount_min: 250000,
    amount_max: 75000000,
    non_cash_support: 'Pre-investment support',
    eligibility_summary: 'Funding for majority black-owned businesses (at least 51%) for expansion, acquisition, or establishing new ventures. Includes Women Empowerment.',
    required_documents: ['CIPC', 'Tax Clearance', 'B-BBEE Certificate', 'Audited Financials'],
    application_url: 'https://www.nefcorp.co.za/application-portal/',
    source_url: 'https://www.nefcorp.co.za',
    closing_date: 'Rolling',
    frequency: 'Always Open',
    expected_open_month: 'January',
    typical_duration_days: 120,
    preparation_checklist: ['Verify 51%+ black equity B-BBEE affidavit', 'Secure signed off-take agreements'],
    common_rejection_reasons: ['Ownership requirements unmet', 'No proven market access/contracts'],
    contact_email: 'info@nefcorp.co.za',
    contact_phone: '0861 843 633',
    last_verified_at: '2026-05-26T00:00:00Z',
    verification_notes: 'Offers specialized sector funds (Tourism, Arts, Film).',
    confidence_score: 95
  },
  {
    opportunity_id: 'idc_general_005',
    programme_name: 'IDC Manufacturing, Trade, & Agri',
    issuer_name: 'Industrial Development Corporation (IDC)',
    issuer_type: 'National DFI',
    official_status: true,
    status: 'OPEN',
    funding_type: FundingType.HYBRID,
    target_stage: 'Growth',
    legal_form_required: ['Private Company', 'Public Company'],
    sector_tags: ['Agriculture', 'Manufacturing', 'Trade'],
    geo_scope: 'National',
    amount_min: 1000000,
    amount_max: 250000000,
    non_cash_support: 'Business Planning',
    eligibility_summary: 'State-owned development finance institution fostering inclusive industrial growth. Provides loans, equity, guarantees.',
    required_documents: ['CIPC', 'Tax Clearance', 'Comprehensive Business Plan', 'Off-take Agreements'],
    application_url: 'https://www.idc.co.za',
    source_url: 'https://www.idc.co.za',
    closing_date: 'Rolling',
    frequency: 'Always Open',
    expected_open_month: 'January',
    typical_duration_days: 120,
    preparation_checklist: ['Ensure all licenses are in place', 'Draft comprehensive project viability plan'],
    common_rejection_reasons: ['No environmental assessment approval', 'Misaligned with national industrial policy'],
    contact_email: 'callcentre@idc.co.za',
    contact_phone: '011 269 3000',
    last_verified_at: '2026-05-26T00:00:00Z',
    verification_notes: 'Apply via online portal, highly structured diligence.',
    confidence_score: 96
  },
  {
    opportunity_id: 'landbank_agri_006',
    programme_name: 'Land Bank Agricultural Finance',
    issuer_name: 'Land and Agricultural Bank',
    issuer_type: 'National DFI',
    official_status: true,
    status: 'OPEN',
    funding_type: FundingType.LOAN,
    target_stage: 'Growth',
    legal_form_required: ['Private Company', 'Sole Proprietor', 'Cooperative'],
    sector_tags: ['Agriculture', 'Agro-processing'],
    geo_scope: 'National',
    amount_min: 50000,
    amount_max: 50000000,
    non_cash_support: 'Agricultural Advisory',
    eligibility_summary: 'State-owned bank for agriculture providing loans to farmers and agribusinesses for production and land acquisition.',
    required_documents: ['CIPC', 'Tax Clearance', 'Proof of Land Ownership/Lease'],
    application_url: 'https://www.landbank.co.za',
    source_url: 'https://www.landbank.co.za',
    closing_date: 'Rolling',
    frequency: 'Always Open',
    expected_open_month: 'January',
    typical_duration_days: 90,
    preparation_checklist: ['Secure land lease agreements', 'Obtain agricultural viability reports'],
    common_rejection_reasons: ['No water rights', 'Unfavorable climate analysis'],
    contact_email: 'info@landbank.co.za',
    contact_phone: '086 843 3572',
    last_verified_at: '2026-05-26T00:00:00Z',
    verification_notes: 'Applications through regional offices or online portal.',
    confidence_score: 93
  },
  {
    opportunity_id: 'dbsa_infra_007',
    programme_name: 'DBSA Infrastructure Fund',
    issuer_name: 'Development Bank of SA (DBSA)',
    issuer_type: 'National DFI',
    official_status: true,
    status: 'OPEN',
    funding_type: FundingType.LOAN,
    target_stage: 'Expansion',
    legal_form_required: ['Private Company', 'Public Company'],
    sector_tags: ['Infrastructure', 'Energy', 'Water', 'ICT'],
    geo_scope: 'National',
    amount_min: 5000000,
    amount_max: 500000000,
    non_cash_support: 'Project Preparation',
    eligibility_summary: 'State dev bank for infrastructure and economic projects. Loans and equity for large projects; supply chain SME participation.',
    required_documents: ['CIPC', 'Feasibility Study', 'Environmental Impact Assessment'],
    application_url: 'https://www.dbsa.org',
    source_url: 'https://www.dbsa.org',
    closing_date: 'Rolling',
    frequency: 'Always Open',
    expected_open_month: 'January',
    typical_duration_days: 180,
    preparation_checklist: ['Complete comprehensive feasibility studies', 'Secure guarantees'],
    common_rejection_reasons: ['Project not commercially viable', 'Inadequate environmental clearance'],
    contact_email: 'webmaster@dbsa.org',
    contact_phone: '011 313 3911',
    last_verified_at: '2026-05-26T00:00:00Z',
    verification_notes: 'Targeted largely at infrastructure and macro projects.',
    confidence_score: 94
  },
  {
    opportunity_id: 'ecdc_finance_008',
    programme_name: 'ECDC Risk Capital & Support',
    issuer_name: 'Eastern Cape Dev. Corp (ECDC)',
    issuer_type: 'Provincial DFI',
    official_status: true,
    status: 'OPEN',
    funding_type: FundingType.LOAN,
    target_stage: 'Growth',
    legal_form_required: ['Private Company', 'Close Corporation'],
    sector_tags: ['Manufacturing', 'Green Economy', 'Tourism'],
    geo_scope: 'Eastern Cape',
    amount_min: 100000,
    amount_max: 20000000,
    non_cash_support: 'Business Support',
    eligibility_summary: 'Eastern Cape official dev agency. Offers economic, risk, and incentive funds to localized SME businesses.',
    required_documents: ['CIPC', 'Tax Clearance', 'Proof of EC Operating Address'],
    application_url: 'https://ecdc.finfind.co.za',
    source_url: 'https://www.ecdc.co.za',
    closing_date: 'Rolling',
    frequency: 'Always Open',
    expected_open_month: 'January',
    typical_duration_days: 90,
    preparation_checklist: ['Prove significant operations within the EC', 'Provide job creation estimates'],
    common_rejection_reasons: ['Business HQ located outside Eastern Cape'],
    contact_email: 'info@ecdc.co.za',
    contact_phone: '+27 43 704 5601',
    last_verified_at: '2026-05-26T00:00:00Z',
    verification_notes: 'Includes FinFind portal integration.',
    confidence_score: 95
  },
  {
    opportunity_id: 'gep_sme_009',
    programme_name: 'GEP Financial Assistance',
    issuer_name: 'Gauteng Enterprise Propeller (GEP)',
    issuer_type: 'Provincial DFI',
    official_status: true,
    status: 'OPEN',
    funding_type: FundingType.LOAN,
    target_stage: 'Early Stage',
    legal_form_required: ['Private Company', 'Sole Proprietor'],
    sector_tags: ['Various'],
    geo_scope: 'Gauteng',
    amount_min: 10000,
    amount_max: 5000000,
    non_cash_support: 'Mentorship',
    eligibility_summary: 'Gauteng enterprise dev agency provides start-up, contract, growth loans, and microfinance.',
    required_documents: ['CIPC', 'Tax Clearance', 'Proof of Gauteng Address'],
    application_url: 'https://www.gep.co.za/mygep',
    source_url: 'https://www.gep.co.za',
    closing_date: 'Rolling',
    frequency: 'Always Open',
    expected_open_month: 'January',
    typical_duration_days: 60,
    preparation_checklist: ['Register on MyGEP portal', 'Download specific PDF application forms'],
    common_rejection_reasons: ['Business outside of Gauteng', 'Negative credit un-remediated'],
    contact_email: 'geppenquiries@gep.co.za',
    contact_phone: '087 057 2000',
    last_verified_at: '2026-05-26T00:00:00Z',
    verification_notes: 'Utilizes both MyGEP online forms and PDF downloads.',
    confidence_score: 97
  },
  {
    opportunity_id: 'ithala_kzn_010',
    programme_name: 'Ithala Business & Property Finance',
    issuer_name: 'Ithala Dev. Fin. Corp. (IDFC)',
    issuer_type: 'Provincial DFI',
    official_status: true,
    status: 'OPEN',
    funding_type: FundingType.LOAN,
    target_stage: 'Growth',
    legal_form_required: ['Private Company', 'Close Corporation'],
    sector_tags: ['Property', 'Retail', 'Agriculture'],
    geo_scope: 'KwaZulu-Natal',
    amount_min: 50000,
    amount_max: 20000000,
    non_cash_support: 'Properties & Facilities',
    eligibility_summary: 'KZN provicial DFI offering loans and equity for business and commercial property development, focusing on emerging communities.',
    required_documents: ['CIPC', 'Tax Clearance', 'Business Plan', 'FICA'],
    application_url: 'https://www.ithala.co.za',
    source_url: 'https://www.ithala.co.za',
    closing_date: 'Rolling',
    frequency: 'Always Open',
    expected_open_month: 'January',
    typical_duration_days: 90,
    preparation_checklist: ['Complete online enquiry form'],
    common_rejection_reasons: ['Operations outside KZN'],
    contact_email: 'talktous@ithala.co.za',
    contact_phone: '031 907 8911',
    last_verified_at: '2026-05-26T00:00:00Z',
    verification_notes: 'Strong property and agriculture portfolio.',
    confidence_score: 95
  },
  {
    opportunity_id: 'leda_limpopo_011',
    programme_name: 'LEDA Capex & Franchise Finance',
    issuer_name: 'Limpopo Econ Dev Agency (LEDA)',
    issuer_type: 'Provincial DFI',
    official_status: true,
    status: 'OPEN',
    funding_type: FundingType.LOAN,
    target_stage: 'Growth',
    legal_form_required: ['Private Company'],
    sector_tags: ['Mining', 'Agriculture', 'Tourism'],
    geo_scope: 'Limpopo',
    amount_min: 50000,
    amount_max: 15000000,
    non_cash_support: 'Franchise Advice',
    eligibility_summary: 'Limpopo dev finance agency providing working capital, asset finance, and franchise finance.',
    required_documents: ['CIPC', 'Limpopo Address Proof', 'Franchise/Asset Quotes'],
    application_url: 'https://www.lieda.co.za',
    source_url: 'https://www.lieda.co.za',
    closing_date: 'Rolling',
    frequency: 'Always Open',
    expected_open_month: 'January',
    typical_duration_days: 90,
    preparation_checklist: ['Visit LEDA offices', 'Provide detailed breakdown of working capital/asset needs'],
    common_rejection_reasons: ['Not operational in Limpopo'],
    contact_email: 'info@lieda.co.za',
    contact_phone: '+27 15 633 4700',
    last_verified_at: '2026-05-26T00:00:00Z',
    verification_notes: 'Applications mostly processed via local LEDA offices/enquiry forms.',
    confidence_score: 94
  },
  {
    opportunity_id: 'nwdc_bridge_012',
    programme_name: 'NWDC Contract/Bridging Finance',
    issuer_name: 'North West Dev. Corp (NWDC)',
    issuer_type: 'Provincial DFI',
    official_status: true,
    status: 'OPEN',
    funding_type: FundingType.LOAN,
    target_stage: 'Growth',
    legal_form_required: ['Private Company'],
    sector_tags: ['Construction', 'Supply Chain', 'Services'],
    geo_scope: 'North West',
    amount_min: 100000,
    amount_max: 10000000,
    non_cash_support: 'Contract structuring advice',
    eligibility_summary: 'NW province DFI providing bridging finance for contractors with secured purchase orders or government contracts.',
    required_documents: ['SBD 4 PDF Form', 'Valid Purchase Order/Contract', 'CIPC'],
    application_url: 'https://www.nwdc.co.za',
    source_url: 'https://www.nwdc.co.za',
    closing_date: 'Rolling',
    frequency: 'Always Open',
    expected_open_month: 'January',
    typical_duration_days: 30,
    preparation_checklist: ['Secure an irrevocable letter of payment instruction (cession) from client'],
    common_rejection_reasons: ['Cannot safely cede purchase order payments to NWDC'],
    contact_email: 'info@nwdc.co.za',
    contact_phone: '087 095 9890',
    last_verified_at: '2026-05-26T00:00:00Z',
    verification_notes: 'Fast turnaround for solid secured POs.',
    confidence_score: 94
  },
  {
    opportunity_id: 'fdc_fs_013',
    programme_name: 'FDC SMME Loans',
    issuer_name: 'Free State Dev. Corp (FDC)',
    issuer_type: 'Provincial DFI',
    official_status: true,
    status: 'OPEN',
    funding_type: FundingType.LOAN,
    target_stage: 'Early Stage',
    legal_form_required: ['Private Company', 'Close Corporation'],
    sector_tags: ['Various'],
    geo_scope: 'Free State',
    amount_min: 20000,
    amount_max: 5000000,
    non_cash_support: 'Mentorship',
    eligibility_summary: 'Free State corporate offering business start-up, expansion, and bridging loans to SMMEs.',
    required_documents: ['SMME Support PDF App', 'Business Plan', 'Tax Clearance'],
    application_url: 'https://www.fdc.co.za',
    source_url: 'https://www.fdc.co.za',
    closing_date: 'Rolling',
    frequency: 'Always Open',
    expected_open_month: 'January',
    typical_duration_days: 60,
    preparation_checklist: ['Download and complete SMME Support Form'],
    common_rejection_reasons: ['No operations in Free State'],
    contact_email: 'wecare@fdc.co.za',
    contact_phone: '051 400 1500',
    last_verified_at: '2026-05-26T00:00:00Z',
    verification_notes: 'Paper/PDF application process mainly.',
    confidence_score: 92
  },
  {
    opportunity_id: 'mega_mppu_014',
    programme_name: 'MEGA Loan Products',
    issuer_name: 'Mpumalanga Econ Growth Agency (MEGA)',
    issuer_type: 'Provincial DFI',
    official_status: true,
    status: 'OPEN',
    funding_type: FundingType.LOAN,
    target_stage: 'Growth',
    legal_form_required: ['Private Company', 'Cooperative'],
    sector_tags: ['Various'],
    geo_scope: 'Mpumalanga',
    amount_min: 50000,
    amount_max: 5000000,
    non_cash_support: 'Business Support',
    eligibility_summary: 'Mpumalanga dev agency funding SMMEs and Co-ops providing affordable loan packages.',
    required_documents: ['MEGA Application Form PDF', 'CIPC', 'Tax Clearance'],
    application_url: 'https://www.mega.gov.za',
    source_url: 'https://www.mega.gov.za',
    closing_date: 'Rolling',
    frequency: 'Always Open',
    expected_open_month: 'January',
    typical_duration_days: 60,
    preparation_checklist: ['Perform online eligibility check', 'Complete specific PDF applications'],
    common_rejection_reasons: ['No footprint in Mpumalanga'],
    contact_email: 'info@mega.gov.za',
    contact_phone: '+27 13 492 5818',
    last_verified_at: '2026-05-26T00:00:00Z',
    verification_notes: 'Uses an online pre-eligibility gate before form completion.',
    confidence_score: 95
  },
  {
    opportunity_id: 'casidra_wc_015',
    programme_name: 'Casidra AgriBusiness Finance',
    issuer_name: 'Casidra SOC Ltd',
    issuer_type: 'Provincial DFI',
    official_status: true,
    status: 'OPEN',
    funding_type: FundingType.HYBRID,
    target_stage: 'Growth',
    legal_form_required: ['Private Company', 'Cooperative'],
    sector_tags: ['Agriculture', 'Rural Development'],
    geo_scope: 'Western Cape',
    amount_min: 100000,
    amount_max: 3000000,
    non_cash_support: 'Technical Assistance',
    eligibility_summary: 'Western Cape dev entity supporting rural projects with grants/loans for agriculture and rural ventures.',
    required_documents: ['CIPC', 'Tax Clearance', 'Land Access Proof'],
    application_url: 'https://www.casidra.co.za',
    source_url: 'https://www.casidra.co.za',
    closing_date: 'Rolling',
    frequency: 'Always Open',
    expected_open_month: 'January',
    typical_duration_days: 90,
    preparation_checklist: ['Validate rural water and land rights'],
    common_rejection_reasons: ['Located in purely urban limits', 'Not agricultural focused'],
    contact_email: 'kasidra@casidra.co.za',
    contact_phone: '+27 21 866 8500',
    last_verified_at: '2026-05-26T00:00:00Z',
    verification_notes: 'Strongly focused on rural/agricultural WC initiatives.',
    confidence_score: 93
  },
  {
    opportunity_id: 'ttf_tourism_016',
    programme_name: 'Tourism Transformation Fund (TTF)',
    issuer_name: 'Department of Tourism / NEF',
    issuer_type: 'Sector Specific',
    official_status: true,
    status: 'OPEN',
    funding_type: FundingType.HYBRID,
    target_stage: 'Growth',
    legal_form_required: ['Private Company'],
    sector_tags: ['Tourism', 'Hospitality'],
    geo_scope: 'National',
    amount_min: 1000000,
    amount_max: 10000000,
    non_cash_support: 'Industry Guidance',
    eligibility_summary: 'Fund for capped grants and loan support for black-owned tourism projects. Administered by NEF.',
    required_documents: ['CIPC', 'NEF TTF PDF App', 'B-BBEE Affidavit', 'Tourism Grading'],
    application_url: 'https://www.nefcorp.co.za/tourism-transformation-fund/',
    source_url: 'https://www.tourism.gov.za',
    closing_date: 'Rolling',
    frequency: 'Always Open',
    expected_open_month: 'January',
    typical_duration_days: 120,
    preparation_checklist: ['Ensure 51%+ black ownership in tourism sector', 'Obtain tourism grading if operational'],
    common_rejection_reasons: ['Not recognized as tourism entity'],
    contact_email: 'tourism@nefcorp.co.za',
    contact_phone: '0861 843 633',
    last_verified_at: '2026-05-26T00:00:00Z',
    verification_notes: 'Apply via NEF Application Portal and TTF PDF Guidelines.',
    confidence_score: 97
  },
  {
    opportunity_id: 'bp_private_017',
    programme_name: 'Business Partners Risk Finance',
    issuer_name: 'Business Partners Ltd',
    issuer_type: 'Private/Commercial',
    official_status: false,
    status: 'OPEN',
    funding_type: FundingType.HYBRID,
    target_stage: 'Expansion',
    legal_form_required: ['Private Company'],
    sector_tags: ['Commercial Property', 'General Business'],
    geo_scope: 'National',
    amount_min: 500000,
    amount_max: 50000000,
    non_cash_support: 'Advisory',
    eligibility_summary: 'Private specialist risk-financier for established SMEs offering loans, asset finance, and property finance.',
    required_documents: ['CIPC', 'Audited Financials', 'Business Plan'],
    application_url: 'https://www.businesspartners.co.za',
    source_url: 'https://www.businesspartners.co.za',
    closing_date: 'Rolling',
    frequency: 'Always Open',
    expected_open_month: 'January',
    typical_duration_days: 45,
    preparation_checklist: ['Prepare minimum 2 years audited financial history'],
    common_rejection_reasons: ['Startup with no trading history', 'Inadequate commercial margins'],
    contact_email: 'enquiries@businesspartners.co.za',
    contact_phone: '021 464 3600',
    last_verified_at: '2026-05-26T00:00:00Z',
    verification_notes: 'Private sector risk-finance.',
    confidence_score: 90
  },
  {
    opportunity_id: 'intl_usaid_018',
    programme_name: 'USAID Enterprise Support / Grants',
    issuer_name: 'USAID / DFC',
    issuer_type: 'International Donor',
    official_status: false,
    status: 'OPEN',
    funding_type: FundingType.GRANT,
    target_stage: 'Growth',
    legal_form_required: ['Private Company', 'NGO', 'NPO'],
    sector_tags: ['Trade', 'Agriculture', 'Healthcare', 'Energy'],
    geo_scope: 'National',
    amount_min: 500000,
    amount_max: 20000000,
    non_cash_support: 'Technical Assistance',
    eligibility_summary: 'U.S. donor programs supporting SA SMEs and NPOs via TradeHub, Agri-finance, and direct investments (often via local DFIs).',
    required_documents: ['Project Proposal', 'Financial History', 'SAM.gov registration'],
    application_url: 'https://www.usaid.gov/south-africa',
    source_url: 'https://www.usaid.gov',
    closing_date: 'Rolling',
    frequency: 'Project Calls',
    expected_open_month: 'January',
    typical_duration_days: 180,
    preparation_checklist: ['Monitor USAID/DTI announcements', 'Ensure strict governance/financial audit limits are met'],
    common_rejection_reasons: ['Non-aligned to strategic development goals', 'Inability to pass heavy US compliance procedures'],
    contact_email: 'info@usaid.gov',
    contact_phone: '+27 12 452 2000',
    last_verified_at: '2026-05-26T00:00:00Z',
    verification_notes: 'Normally intermediated by local agencies/funds or broad RFP calls.',
    confidence_score: 85
  }
];

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'a1',
    title: 'First Steps',
    description: 'Created your profile',
    completed: true,
    icon: 'star'
  },
  {
    id: 'a2',
    title: 'Document Master',
    description: 'Upload 5 documents',
    completed: false,
    icon: 'upload'
  },
  {
    id: 'a3',
    title: 'Application Pro',
    description: 'Start 10 applications',
    completed: false,
    icon: 'file-text'
  },
  {
    id: 'a4',
    title: 'Success Story',
    description: 'Get funding approved',
    completed: false,
    icon: 'trophy'
  }
];
