
import { FundingType, FundingOpportunityDb, Achievement } from './types';

export const MOCK_FUNDING: FundingOpportunityDb[] = [
  {
    opportunity_id: 'nyda_grant_001',
    programme_name: 'NYDA Micro Finance Grant',
    issuer_name: 'National Youth Development Agency (NYDA)',
    issuer_type: 'Government Agency',
    official_status: true,
    status: 'OPEN',
    funding_type: FundingType.GRANT,
    target_stage: 'Early Stage',
    legal_form_required: ['Private Company', 'Sole Proprietor', 'Cooperative'],
    sector_tags: ['Any'],
    geo_scope: 'National',
    amount_min: 1000,
    amount_max: 200000,
    non_cash_support: 'Business Management Training',
    eligibility_summary: 'Targeted at youth entrepreneurs (18-35 years) to acquire equipment, stock, or formalization. Must possess skills or experience related to the business.',
    required_documents: ['ID', 'Proof of Address', 'Business Plan', 'Quotations', 'Banking Details'],
    application_url: 'https://erp.nyda.gov.za/',
    source_url: 'https://www.nyda.gov.za/',
    closing_date: 'Rolling',
    frequency: 'Rolling, Batch-based',
    expected_open_month: 'January',
    typical_duration_days: 90,
    preparation_checklist: ['Complete NYDA Business Management Training Course', 'Get 3 formal quotes for equipment/stock', 'Ensure tax clearance is valid', 'Update business plan tailored to NYDA template'],
    common_rejection_reasons: ['Quotes not from official registered suppliers', 'Applicant over 35 years old', 'Missing NYDA training certificate'],
    contact_email: 'info@nyda.gov.za',
    contact_phone: '0800 52 52 52',
    last_verified_at: '2026-05-01T00:00:00Z',
    verification_notes: 'Verified via ERP portal. Currently open for batch processing.',
    confidence_score: 98
  },
  {
    opportunity_id: 'tia_seed_002',
    programme_name: 'TIA Seed Fund',
    issuer_name: 'Technology Innovation Agency',
    issuer_type: 'Government Agency',
    official_status: true,
    status: 'UPCOMING',
    funding_type: FundingType.GRANT,
    target_stage: 'Concept/Prototype',
    legal_form_required: ['Private Company'],
    sector_tags: ['Technology', 'Innovation', 'BioTech', 'ICT'],
    geo_scope: 'National',
    amount_min: 50000,
    amount_max: 500000,
    non_cash_support: 'Incubation Support',
    eligibility_summary: 'Designed to assist technology innovators and SMMEs to advance their research and development, and validate prototypes.',
    required_documents: ['CIPC', 'Tax Clearance', 'Pitch Deck', 'IP Registration (Optional)', 'Detailed Budget'],
    application_url: 'https://www.tia.org.za/seed-fund/',
    source_url: 'https://www.tia.org.za',
    closing_date: '2026-09-30',
    frequency: 'Annual',
    expected_open_month: 'September',
    typical_duration_days: 30,
    preparation_checklist: ['Draft a clear R&D milestone plan', 'Prepare technical proof of concept documentation', 'Register IP or secure freedom to operate', 'Engage a local TIA implementing agency (university/incubator)'],
    common_rejection_reasons: ['Technology is not sufficiently innovative', 'Lack of commercialization strategy', 'Applied directly without an implementing partner'],
    contact_email: 'customerservice@tia.org.za',
    contact_phone: '012 472 2701',
    last_verified_at: '2026-05-02T00:00:00Z',
    verification_notes: 'Expected to open in September. Preparation highly recommended now.',
    confidence_score: 95
  },
  {
    opportunity_id: 'sefa_direct_003',
    programme_name: 'Direct Lending Facility',
    issuer_name: 'Small Enterprise Finance Agency (sefa)',
    issuer_type: 'Government Agency',
    official_status: true,
    status: 'OPEN',
    funding_type: FundingType.LOAN,
    target_stage: 'Growth',
    legal_form_required: ['Private Company', 'Close Corporation', 'Cooperative'],
    sector_tags: ['Manufacturing', 'Agriculture', 'Services'],
    geo_scope: 'National',
    amount_min: 50000,
    amount_max: 15000000,
    non_cash_support: 'Mentorship',
    eligibility_summary: 'Bridging loans, term loans, and revolving credit for SMMEs needing working capital or asset finance.',
    required_documents: ['CIPC', 'Tax Clearance', 'FICA', '6 Months Bank Statements', 'Financial Projections', 'Management Accounts'],
    application_url: 'https://www.sefa.org.za/products/direct-lending',
    source_url: 'https://www.sefa.org.za',
    closing_date: 'Rolling',
    frequency: 'Always Open',
    expected_open_month: 'January',
    typical_duration_days: 365,
    preparation_checklist: ['Ensure management accounts are up to date within 3 months', 'Prepare a clear cash flow forecast matching the loan repayment terms', 'Secure personal surety or collateral details if applicable'],
    common_rejection_reasons: ['Poor credit record of directors', 'Unrealistic financial projections', 'Inadequate historical cash flow to service debt'],
    contact_email: 'helpline@sefa.org.za',
    contact_phone: '012 748 9600',
    last_verified_at: '2026-05-01T00:00:00Z',
    verification_notes: 'Constantly open but processing times can be lengthy.',
    confidence_score: 90
  },
  {
    opportunity_id: 'cdsp_coop_004',
    programme_name: 'Co-operative Development Support Programme (CDSP)',
    issuer_name: 'Department of Small Business Development (DSBD)',
    issuer_type: 'Government Agency',
    official_status: true,
    status: 'CLOSED',
    funding_type: FundingType.GRANT,
    target_stage: 'Early Stage',
    legal_form_required: ['Cooperative'],
    sector_tags: ['Agriculture', 'Manufacturing', 'Retail', 'Services'],
    geo_scope: 'National',
    amount_min: 100000,
    amount_max: 2500000,
    non_cash_support: 'Market Access & Mentorship',
    eligibility_summary: 'Offers blended financing to registered co-operatives to support acquiring machinery, working capital, and commercialization.',
    required_documents: ['Co-operative Registration Certificate', 'Constitution', 'Tax Clearance', 'Signed Members Resolution', 'Business Plan'],
    application_url: 'http://www.dsbd.gov.za/programme/cdsp',
    source_url: 'http://www.dsbd.gov.za',
    closing_date: '2026-03-31',
    frequency: 'Annual',
    expected_open_month: 'March',
    typical_duration_days: 45,
    preparation_checklist: ['Draft and sign co-operative members resolutions', 'Update the cooperative\'s constitution', 'Ensure all members have zero tax compliance issues'],
    common_rejection_reasons: ['Not a registered co-operative', 'Less than minimum required members (usually 5)', 'Missing member resolutions'],
    contact_email: 'cdsp@dsbd.gov.za',
    contact_phone: '0861 843 384',
    last_verified_at: '2026-04-15T00:00:00Z',
    verification_notes: 'Currently closed. Expected to re-open next March.',
    confidence_score: 99
  },
  {
    opportunity_id: 'nef_women_005',
    programme_name: 'Women Empowerment Fund',
    issuer_name: 'National Empowerment Fund (NEF)',
    issuer_type: 'Development Finance Institution',
    official_status: true,
    status: 'OPEN',
    funding_type: FundingType.LOAN,
    target_stage: 'Growth',
    legal_form_required: ['Private Company', 'Close Corporation'],
    sector_tags: ['Any'],
    geo_scope: 'National',
    amount_min: 250000,
    amount_max: 75000000,
    non_cash_support: 'Pre-investment support',
    eligibility_summary: 'Funding for majority black-women-owned businesses (at least 51%) for expansion, acquisition, or establishing new ventures.',
    required_documents: ['CIPC', 'Tax Clearance', 'B-BBEE Certificate', 'Audited Financials', 'Off-take Agreements (if applicable)'],
    application_url: 'https://www.nefcorp.co.za/products-services/women-empowerment-fund/',
    source_url: 'https://www.nefcorp.co.za',
    closing_date: 'Rolling',
    frequency: 'Always Open',
    expected_open_month: 'January',
    typical_duration_days: 365,
    preparation_checklist: ['Obtain a valid B-BBEE affidavit/certificate proving 51%+ black women ownership', 'Secure signed off-take agreements or contracts to prove market demand', 'Prepare 3-5 years robust financial projections'],
    common_rejection_reasons: ['Less than 51% black women ownership', 'No proven market access/contracts', 'Insufficient commercial viability'],
    contact_email: 'applications@nefcorp.co.za',
    contact_phone: '011 305 8000',
    last_verified_at: '2026-05-01T00:00:00Z',
    verification_notes: 'Highly competitive and requires significant operational readiness.',
    confidence_score: 94
  }
];

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'a1',
    title: 'First Steps',
    description: 'Created your profile',
    completed: true,
    icon: 'star'
  },
  {
    id: 'a2',
    title: 'Document Master',
    description: 'Upload 5 documents',
    completed: false,
    icon: 'upload'
  },
  {
    id: 'a3',
    title: 'Application Pro',
    description: 'Start 10 applications',
    completed: false,
    icon: 'file-text'
  },
  {
    id: 'a4',
    title: 'Success Story',
    description: 'Get funding approved',
    completed: false,
    icon: 'trophy'
  }
];
